// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI44-TiirQyXSfGLvfYfvOZ7_Jhu6c86k',
    appId: '1:824456597108:web:b3be53651862d2e8744b21',
    messagingSenderId: '824456597108',
    projectId: 'kigali-directory-4d66c',
    authDomain: 'kigali-directory-4d66c.firebaseapp.com',
    storageBucket: 'kigali-directory-4d66c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV-P1-Bqa8_6fLk-AV_cvtcm21T50C-cI',
    appId: '1:824456597108:ios:81b4551aeb263c1e744b21',
    messagingSenderId: '824456597108',
    projectId: 'kigali-directory-4d66c',
    storageBucket: 'kigali-directory-4d66c.firebasestorage.app',
    iosBundleId: 'com.kigali.kigaliDirectory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0vjcMoPGBnxwILDldaG_caOqRxj8T-GI',
    appId: '1:824456597108:ios:81b4551aeb263c1e744b21',
    messagingSenderId: '824456597108',
    projectId: 'kigali-directory-4d66c',
    storageBucket: 'kigali-directory-4d66c.firebasestorage.app',
    iosBundleId: 'com.kigali.kigaliDirectory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI44-TiirQyXSfGLvfYfvOZ7_Jhu6c86k',
    appId: '1:824456597108:web:f78effec7d5c4aed744b21',
    messagingSenderId: '824456597108',
    projectId: 'kigali-directory-4d66c',
    authDomain: 'kigali-directory-4d66c.firebaseapp.com',
    storageBucket: 'kigali-directory-4d66c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCThxyDhZS0yuAgT9CdQdCUxmGFLiWCKgA',
    appId: '1:824456597108:android:69c28feffa86904b744b21',
    messagingSenderId: '824456597108',
    projectId: 'kigali-directory-4d66c',
    storageBucket: 'kigali-directory-4d66c.firebasestorage.app',
  );

}